import { balloonMaterials, useGame } from "../hooks/useGame.ts"
import { PositionalAudio, useGLTF } from "@react-three/drei"
import { type CollisionPayload, ConvexHullCollider, type RapierRigidBody, RigidBody } from "@react-three/rapier"
import { useCallback, useEffect, useRef, useState } from "react"
import { VFXEmitter } from "wawa-vfx"
import { Vector3 } from "three"
import { useFrame } from "@react-three/fiber"
import { randFloat } from "three/src/math/MathUtils"
import { AUDIOS } from "../consts.ts"

export const Balloons = () => {
  const balloons = useGame((state) => state.balloons)
  return balloons.map((balloon) => <Balloon key={balloon.id} {...balloon} />)
}

const Balloon = ({ position, color }) => {
  const rb = useRef<RapierRigidBody | null>(null) // rigid body

  const { nodes, materials } = useGLTF("models/Balloon.glb")
  const [exploded, setExploded] = useState(false)
  const onBalloonHit = useGame((state) => state.onBalloonHit)

  const onIntersectionEnter = useCallback((e: CollisionPayload) => {
    if (e.other.rigidBodyObject?.name === "axe") {
      setExploded(true)
    }
  }, [])

  const isCustomMaterial = true
  const customMaterial = isCustomMaterial ? balloonMaterials[color] : materials.phong1SG

  useEffect(() => {
    if (exploded) {
      onBalloonHit()
    }
  }, [exploded, onBalloonHit])

  useEffect(() => {
    if (rb.current) {
      rb.current.applyTorqueImpulse(new Vector3(Math.random() * 0.05, Math.random() * 0.05, Math.random() * 0.05), true)
    } // ...avoid them diverging from center while they bounce off each other
  }, []) // spread rising balloons randomly...

  useFrame(() => {
    if (rb.current && !exploded) {
      const currTranslation = rb.current.translation()
      if (currTranslation.y > 20) {
        currTranslation.y = randFloat(-20, -15)
        rb.current.setLinvel(new Vector3(0, 0, 0), false)
        rb.current.setAngvel(new Vector3(0, 0, 0), false)
        rb.current.applyTorqueImpulse(
          new Vector3(Math.random() * 0.05, Math.random() * 0.05, Math.random() * 0.05),
          true
        )
      }
      rb.current.setTranslation(currTranslation, true) // since, we impacted the translation
    }
  }) // respawn exploded balloons from the start position

  return (
    <RigidBody
      ref={rb}
      position={position}
      type="dynamic"
      gravityScale={-0.1}
      mass={0.1}
      linearDamping={0.2}
      angularDamping={0.2}
      restitution={1}
      // NOTE: Due to balloon string, avoid colliders="hull" here
      onIntersectionEnter={onIntersectionEnter}
    >
      {exploded && (
        <>
          <PositionalAudio url={AUDIOS.pop} autoplay={true} loop={false} distance={10} />
          <VFXEmitter
            emitter="sparks"
            settings={{
              loop: false,
              spawnMode: "burst",
              nbParticles: 100,
              duration: 1,
              size: [0.05, 0.3],
              startPositionMin: [-0.1, -0.1, -0.1],
              startPositionMax: [0.1, 0.1, 0.1],
              directionMin: [-0.1, 0, -0.1],
              directionMax: [0.1, 0.5, 0.1],
              rotationSpeedMin: [-1, -1, -10],
              rotationSpeedMax: [1, 1, 10],
              speed: [1, 7],
              colorStart: [color],
              particlesLifetime: [0.1, 1],
            }}
          />
        </>
      )}
      <group scale={3} visible={!exploded}>
        <ConvexHullCollider args={[nodes.Balloon007.geometry.attributes.position.array]} />
        <mesh // force-line-break
          castShadow={false}
          receiveShadow={false}
          geometry={nodes.Balloon007.geometry}
          material={customMaterial}
        />
      </group>
    </RigidBody>
  ) // Auto-generated by: https://github.com/pmndrs/gltfjsx
}
